FROM apache/airflow:2.7.3-python3.9

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Copie et installation des requirements
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Installation des providers Airflow
# On force urllib3 une dernière fois ici pour être sûr que les providers ne le mettent pas à jour
RUN pip install --no-cache-dir "urllib3<2.0" \
    apache-airflow-providers-postgres \
    apache-airflow-providers-amazon